### ISSUE TITLE
Not showing selected or reviewer notes message in review window

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#419] opened 2016-11-02 12:23 UTC
Not yet showing the selected criteria in the pop-up window, nor the reviewer comments.

Wonder if it's looking at the selected criteria and comments from the

 logged in user rather than the user who did the review?

Image - with this one the medical review had selected a couple of the criteria and added some comments:
![rejected](https://cloud.githubusercontent.com/assets/344917/19928629/eac4a042-a107-11e6-9061-a8bd39e643a0.png)

**Comment by bennylope** [comment] 2016-11-17 16:57
Duplicate of #408

**Closed by bennylope** 2016-11-17 16:57 UTC
Labels: bug, medium priority
